//! A [SystemLookup] with generated test data.

////////////////////////////////////////////////////////////////////////////////////
// --- module uses ---
////////////////////////////////////////////////////////////////////////////////////
use crate::SystemLookup;
use once_cell::sync::Lazy;
use plus_modeled::SystemId;
use std::collections::HashMap;

// α <mod-def generated_system_lookup>
// ω <mod-def generated_system_lookup>

pub static GENERATED_SYSTEM_LOOKUP: Lazy<SystemLookup> = Lazy::new(|| SystemLookup {
    users: HashMap::from([
        (0, "plusauri".to_string()),
        (1, "wealthy_barber".to_string()),
        (2, "tony_stark".to_string()),
        (3, "chris_p_bacon".to_string()),
    ]),
    outlooks: HashMap::from([
        (0, "Standard".to_string()),
        (1, "Gloomy".to_string()),
        (2, "Bright".to_string()),
        (3, "HoldOnTight".to_string()),
    ]),
    growth_items: HashMap::from([
        (
            SystemId::WorthItemId(0),
            "ResidentialRealEstate".to_string(),
        ),
        (SystemId::WorthItemId(1), "CommercialRealEstate".to_string()),
        (SystemId::WorthItemId(2), "FamilyFarm".to_string()),
        (SystemId::WorthItemId(3), "Automobile".to_string()),
        (SystemId::WorthItemId(4), "ClassicCar".to_string()),
        (SystemId::WorthItemId(5), "AntiqueCar".to_string()),
        (SystemId::WorthItemId(6), "VintageCar".to_string()),
        (SystemId::WorthItemId(7), "Boat".to_string()),
        (SystemId::WorthItemId(8), "Toys".to_string()),
        (SystemId::WorthItemId(9), "OtherWorth".to_string()),
        (SystemId::HoldingItemId(0), "UsEquitySample".to_string()),
        (SystemId::HoldingItemId(1), "UsEquityMarket".to_string()),
        (
            SystemId::HoldingItemId(2),
            "UsLargeEquityMarket".to_string(),
        ),
        (
            SystemId::HoldingItemId(3),
            "UsLargeEquitySample".to_string(),
        ),
        (
            SystemId::HoldingItemId(4),
            "UsSmallEquityMarket".to_string(),
        ),
        (
            SystemId::HoldingItemId(5),
            "UsSmallEquitySample".to_string(),
        ),
        (SystemId::HoldingItemId(6), "UsMidEquityMarket".to_string()),
        (SystemId::HoldingItemId(7), "UsMidEquitySample".to_string()),
        (
            SystemId::HoldingItemId(8),
            "EmergingEquityMarket".to_string(),
        ),
        (
            SystemId::HoldingItemId(9),
            "EmergingEquityMarketSample".to_string(),
        ),
        (SystemId::HoldingItemId(10), "Gold".to_string()),
        (SystemId::HoldingItemId(11), "Tips".to_string()),
        (SystemId::HoldingItemId(12), "RealEstate".to_string()),
        (SystemId::HoldingItemId(13), "DevelopedMarkets".to_string()),
        (
            SystemId::HoldingItemId(14),
            "DevelopedMarketsSample".to_string(),
        ),
        (SystemId::HoldingItemId(15), "UsHighYieldBonds".to_string()),
        (SystemId::HoldingItemId(16), "Commodities".to_string()),
        (
            SystemId::HoldingItemId(17),
            "UsLongTermTreasury".to_string(),
        ),
        (
            SystemId::HoldingItemId(18),
            "UsIntermediateTermTreasury".to_string(),
        ),
        (
            SystemId::HoldingItemId(19),
            "UsShortTermTreasury".to_string(),
        ),
        (
            SystemId::HoldingItemId(20),
            "UsShortTermCorporateBond".to_string(),
        ),
        (
            SystemId::HoldingItemId(21),
            "UsLongTermCorporateBond".to_string(),
        ),
        (SystemId::HoldingItemId(22), "UsMoneyMarket".to_string()),
        (
            SystemId::HoldingItemId(23),
            "InternationalBonds".to_string(),
        ),
        (
            SystemId::HoldingItemId(24),
            "CertificateOfDeposit".to_string(),
        ),
        (SystemId::HoldingItemId(25), "OtherInstrument".to_string()),
        (SystemId::FlowItemId(0), "EarnedIncome".to_string()),
        (SystemId::FlowItemId(1), "PensionIncome".to_string()),
        (SystemId::FlowItemId(2), "SocialSecurityIncome".to_string()),
        (SystemId::FlowItemId(3), "RentalIncome".to_string()),
        (SystemId::FlowItemId(4), "RoyaltyIncome".to_string()),
        (
            SystemId::FlowItemId(5),
            "InternetAdvertisingIncome".to_string(),
        ),
        (SystemId::FlowItemId(6), "PassiveBusinessIncome".to_string()),
        (SystemId::FlowItemId(7), "OrdinaryIncome".to_string()),
        (SystemId::FlowItemId(8), "LivingExpense".to_string()),
        (SystemId::FlowItemId(9), "HealthCareExpense".to_string()),
        (SystemId::FlowItemId(10), "CollegeExpense".to_string()),
        (SystemId::FlowItemId(11), "PropertyTaxes".to_string()),
        (SystemId::FlowItemId(12), "MortgageInterest".to_string()),
        (SystemId::FlowItemId(13), "StateTaxesPaid".to_string()),
        (SystemId::FlowItemId(14), "CharitableDonations".to_string()),
        (SystemId::FlowItemId(15), "MedicalExpenses".to_string()),
        (SystemId::FlowItemId(16), "RetirementCredits".to_string()),
        (SystemId::FlowItemId(17), "IraContributions".to_string()),
        (SystemId::FlowItemId(18), "OtherInFlow".to_string()),
        (SystemId::FlowItemId(19), "OtherOutFlow".to_string()),
    ]),
    instruments: HashMap::from([
        (SystemId::InstrumentId(0), "A".to_string()),
        (SystemId::InstrumentId(1), "AAL".to_string()),
        (SystemId::InstrumentId(2), "AAP".to_string()),
        (SystemId::InstrumentId(3), "AAPL".to_string()),
        (SystemId::InstrumentId(4), "ABBV".to_string()),
        (SystemId::InstrumentId(5), "ABC".to_string()),
        (SystemId::InstrumentId(6), "ABMD".to_string()),
        (SystemId::InstrumentId(7), "ABT".to_string()),
        (SystemId::InstrumentId(8), "ACN".to_string()),
        (SystemId::InstrumentId(9), "ADBE".to_string()),
        (SystemId::InstrumentId(10), "ADI".to_string()),
        (SystemId::InstrumentId(11), "ADM".to_string()),
        (SystemId::InstrumentId(12), "ADP".to_string()),
        (SystemId::InstrumentId(13), "ADSK".to_string()),
        (SystemId::InstrumentId(14), "AEE".to_string()),
        (SystemId::InstrumentId(15), "AEP".to_string()),
        (SystemId::InstrumentId(16), "AES".to_string()),
        (SystemId::InstrumentId(17), "AFL".to_string()),
        (SystemId::InstrumentId(18), "AIG".to_string()),
        (SystemId::InstrumentId(19), "AIZ".to_string()),
        (SystemId::InstrumentId(20), "AJG".to_string()),
        (SystemId::InstrumentId(21), "AKAM".to_string()),
        (SystemId::InstrumentId(22), "ALB".to_string()),
        (SystemId::InstrumentId(23), "ALGN".to_string()),
        (SystemId::InstrumentId(24), "ALK".to_string()),
        (SystemId::InstrumentId(25), "ALL".to_string()),
        (SystemId::InstrumentId(26), "ALLE".to_string()),
        (SystemId::InstrumentId(27), "AMAT".to_string()),
        (SystemId::InstrumentId(28), "AMCR".to_string()),
        (SystemId::InstrumentId(29), "AMD".to_string()),
        (SystemId::InstrumentId(30), "AME".to_string()),
        (SystemId::InstrumentId(31), "AMGN".to_string()),
        (SystemId::InstrumentId(32), "AMP".to_string()),
        (SystemId::InstrumentId(33), "AMT".to_string()),
        (SystemId::InstrumentId(34), "AMZN".to_string()),
        (SystemId::InstrumentId(35), "ANET".to_string()),
        (SystemId::InstrumentId(36), "ANSS".to_string()),
        (SystemId::InstrumentId(37), "AON".to_string()),
        (SystemId::InstrumentId(38), "AOS".to_string()),
        (SystemId::InstrumentId(39), "APA".to_string()),
        (SystemId::InstrumentId(40), "APD".to_string()),
        (SystemId::InstrumentId(41), "APH".to_string()),
        (SystemId::InstrumentId(42), "APTV".to_string()),
        (SystemId::InstrumentId(43), "ARE".to_string()),
        (SystemId::InstrumentId(44), "ATO".to_string()),
        (SystemId::InstrumentId(45), "ATVI".to_string()),
        (SystemId::InstrumentId(46), "AVB".to_string()),
        (SystemId::InstrumentId(47), "AVGO".to_string()),
        (SystemId::InstrumentId(48), "AVY".to_string()),
        (SystemId::InstrumentId(49), "AWK".to_string()),
        (SystemId::InstrumentId(50), "AXP".to_string()),
        (SystemId::InstrumentId(51), "AZO".to_string()),
        (SystemId::InstrumentId(52), "BA".to_string()),
        (SystemId::InstrumentId(53), "BAC".to_string()),
        (SystemId::InstrumentId(54), "BALL".to_string()),
        (SystemId::InstrumentId(55), "BAX".to_string()),
        (SystemId::InstrumentId(56), "BBWI".to_string()),
        (SystemId::InstrumentId(57), "BBY".to_string()),
        (SystemId::InstrumentId(58), "BDX".to_string()),
        (SystemId::InstrumentId(59), "BEN".to_string()),
        (SystemId::InstrumentId(60), "BF.B".to_string()),
        (SystemId::InstrumentId(61), "BIIB".to_string()),
        (SystemId::InstrumentId(62), "BIO".to_string()),
        (SystemId::InstrumentId(63), "BK".to_string()),
        (SystemId::InstrumentId(64), "BKNG".to_string()),
        (SystemId::InstrumentId(65), "BKR".to_string()),
        (SystemId::InstrumentId(66), "BLK".to_string()),
        (SystemId::InstrumentId(67), "BMY".to_string()),
        (SystemId::InstrumentId(68), "BR".to_string()),
        (SystemId::InstrumentId(69), "BRK.B".to_string()),
        (SystemId::InstrumentId(70), "BRO".to_string()),
        (SystemId::InstrumentId(71), "BSX".to_string()),
        (SystemId::InstrumentId(72), "BWA".to_string()),
        (SystemId::InstrumentId(73), "BXP".to_string()),
        (SystemId::InstrumentId(74), "C".to_string()),
        (SystemId::InstrumentId(75), "CAG".to_string()),
        (SystemId::InstrumentId(76), "CAH".to_string()),
        (SystemId::InstrumentId(77), "CARR".to_string()),
        (SystemId::InstrumentId(78), "CAT".to_string()),
        (SystemId::InstrumentId(79), "CB".to_string()),
        (SystemId::InstrumentId(80), "CBOE".to_string()),
        (SystemId::InstrumentId(81), "CBRE".to_string()),
        (SystemId::InstrumentId(82), "CCI".to_string()),
        (SystemId::InstrumentId(83), "CCL".to_string()),
        (SystemId::InstrumentId(84), "CDAY".to_string()),
        (SystemId::InstrumentId(85), "CDNS".to_string()),
        (SystemId::InstrumentId(86), "CDW".to_string()),
        (SystemId::InstrumentId(87), "CE".to_string()),
        (SystemId::InstrumentId(88), "CEG".to_string()),
        (SystemId::InstrumentId(89), "CF".to_string()),
        (SystemId::InstrumentId(90), "CFG".to_string()),
        (SystemId::InstrumentId(91), "CHD".to_string()),
        (SystemId::InstrumentId(92), "CHRW".to_string()),
        (SystemId::InstrumentId(93), "CHTR".to_string()),
        (SystemId::InstrumentId(94), "CI".to_string()),
        (SystemId::InstrumentId(95), "CINF".to_string()),
        (SystemId::InstrumentId(96), "CL".to_string()),
        (SystemId::InstrumentId(97), "CLX".to_string()),
        (SystemId::InstrumentId(98), "CMA".to_string()),
        (SystemId::InstrumentId(99), "CMCSA".to_string()),
        (SystemId::InstrumentId(100), "CME".to_string()),
        (SystemId::InstrumentId(101), "CMG".to_string()),
        (SystemId::InstrumentId(102), "CMI".to_string()),
        (SystemId::InstrumentId(103), "CMS".to_string()),
        (SystemId::InstrumentId(104), "CNC".to_string()),
        (SystemId::InstrumentId(105), "CNP".to_string()),
        (SystemId::InstrumentId(106), "COF".to_string()),
        (SystemId::InstrumentId(107), "COO".to_string()),
        (SystemId::InstrumentId(108), "COP".to_string()),
        (SystemId::InstrumentId(109), "COST".to_string()),
        (SystemId::InstrumentId(110), "CPB".to_string()),
        (SystemId::InstrumentId(111), "CPRT".to_string()),
        (SystemId::InstrumentId(112), "CPT".to_string()),
        (SystemId::InstrumentId(113), "CRL".to_string()),
        (SystemId::InstrumentId(114), "CRM".to_string()),
        (SystemId::InstrumentId(115), "CSCO".to_string()),
        (SystemId::InstrumentId(116), "CSGP".to_string()),
        (SystemId::InstrumentId(117), "CSX".to_string()),
        (SystemId::InstrumentId(118), "CTAS".to_string()),
        (SystemId::InstrumentId(119), "CTLT".to_string()),
        (SystemId::InstrumentId(120), "CTRA".to_string()),
        (SystemId::InstrumentId(121), "CTSH".to_string()),
        (SystemId::InstrumentId(122), "CTVA".to_string()),
        (SystemId::InstrumentId(123), "CVS".to_string()),
        (SystemId::InstrumentId(124), "CVX".to_string()),
        (SystemId::InstrumentId(125), "CZR".to_string()),
        (SystemId::InstrumentId(126), "D".to_string()),
        (SystemId::InstrumentId(127), "DAL".to_string()),
        (SystemId::InstrumentId(128), "DD".to_string()),
        (SystemId::InstrumentId(129), "DE".to_string()),
        (SystemId::InstrumentId(130), "DFS".to_string()),
        (SystemId::InstrumentId(131), "DG".to_string()),
        (SystemId::InstrumentId(132), "DGX".to_string()),
        (SystemId::InstrumentId(133), "DHI".to_string()),
        (SystemId::InstrumentId(134), "DHR".to_string()),
        (SystemId::InstrumentId(135), "DIS".to_string()),
        (SystemId::InstrumentId(136), "DISH".to_string()),
        (SystemId::InstrumentId(137), "DLR".to_string()),
        (SystemId::InstrumentId(138), "DLTR".to_string()),
        (SystemId::InstrumentId(139), "DOV".to_string()),
        (SystemId::InstrumentId(140), "DOW".to_string()),
        (SystemId::InstrumentId(141), "DPZ".to_string()),
        (SystemId::InstrumentId(142), "DRI".to_string()),
        (SystemId::InstrumentId(143), "DTE".to_string()),
        (SystemId::InstrumentId(144), "DUK".to_string()),
        (SystemId::InstrumentId(145), "DVA".to_string()),
        (SystemId::InstrumentId(146), "DVN".to_string()),
        (SystemId::InstrumentId(147), "DXC".to_string()),
        (SystemId::InstrumentId(148), "DXCM".to_string()),
        (SystemId::InstrumentId(149), "EA".to_string()),
        (SystemId::InstrumentId(150), "EBAY".to_string()),
        (SystemId::InstrumentId(151), "ECL".to_string()),
        (SystemId::InstrumentId(152), "ED".to_string()),
        (SystemId::InstrumentId(153), "EFX".to_string()),
        (SystemId::InstrumentId(154), "EIX".to_string()),
        (SystemId::InstrumentId(155), "EL".to_string()),
        (SystemId::InstrumentId(156), "ELV".to_string()),
        (SystemId::InstrumentId(157), "EMN".to_string()),
        (SystemId::InstrumentId(158), "EMR".to_string()),
        (SystemId::InstrumentId(159), "ENPH".to_string()),
        (SystemId::InstrumentId(160), "EOG".to_string()),
        (SystemId::InstrumentId(161), "EPAM".to_string()),
        (SystemId::InstrumentId(162), "EQIX".to_string()),
        (SystemId::InstrumentId(163), "EQR".to_string()),
        (SystemId::InstrumentId(164), "EQT".to_string()),
        (SystemId::InstrumentId(165), "ES".to_string()),
        (SystemId::InstrumentId(166), "ESS".to_string()),
        (SystemId::InstrumentId(167), "ETN".to_string()),
        (SystemId::InstrumentId(168), "ETR".to_string()),
        (SystemId::InstrumentId(169), "ETSY".to_string()),
        (SystemId::InstrumentId(170), "EVRG".to_string()),
        (SystemId::InstrumentId(171), "EW".to_string()),
        (SystemId::InstrumentId(172), "EXC".to_string()),
        (SystemId::InstrumentId(173), "EXPD".to_string()),
        (SystemId::InstrumentId(174), "EXPE".to_string()),
        (SystemId::InstrumentId(175), "EXR".to_string()),
        (SystemId::InstrumentId(176), "F".to_string()),
        (SystemId::InstrumentId(177), "FANG".to_string()),
        (SystemId::InstrumentId(178), "FAST".to_string()),
        (SystemId::InstrumentId(179), "FBHS".to_string()),
        (SystemId::InstrumentId(180), "FCX".to_string()),
        (SystemId::InstrumentId(181), "FDS".to_string()),
        (SystemId::InstrumentId(182), "FDX".to_string()),
        (SystemId::InstrumentId(183), "FE".to_string()),
        (SystemId::InstrumentId(184), "FFIV".to_string()),
        (SystemId::InstrumentId(185), "FIS".to_string()),
        (SystemId::InstrumentId(186), "FISV".to_string()),
        (SystemId::InstrumentId(187), "FITB".to_string()),
        (SystemId::InstrumentId(188), "FLT".to_string()),
        (SystemId::InstrumentId(189), "FMC".to_string()),
        (SystemId::InstrumentId(190), "FOX".to_string()),
        (SystemId::InstrumentId(191), "FOXA".to_string()),
        (SystemId::InstrumentId(192), "FRC".to_string()),
        (SystemId::InstrumentId(193), "FRT".to_string()),
        (SystemId::InstrumentId(194), "FTNT".to_string()),
        (SystemId::InstrumentId(195), "FTV".to_string()),
        (SystemId::InstrumentId(196), "GD".to_string()),
        (SystemId::InstrumentId(197), "GE".to_string()),
        (SystemId::InstrumentId(198), "GILD".to_string()),
        (SystemId::InstrumentId(199), "GIS".to_string()),
        (SystemId::InstrumentId(200), "GL".to_string()),
        (SystemId::InstrumentId(201), "GLW".to_string()),
        (SystemId::InstrumentId(202), "GM".to_string()),
        (SystemId::InstrumentId(203), "GNRC".to_string()),
        (SystemId::InstrumentId(204), "GOOG".to_string()),
        (SystemId::InstrumentId(205), "GOOGL".to_string()),
        (SystemId::InstrumentId(206), "GPC".to_string()),
        (SystemId::InstrumentId(207), "GPN".to_string()),
        (SystemId::InstrumentId(208), "GRMN".to_string()),
        (SystemId::InstrumentId(209), "GS".to_string()),
        (SystemId::InstrumentId(210), "GWW".to_string()),
        (SystemId::InstrumentId(211), "HAL".to_string()),
        (SystemId::InstrumentId(212), "HAS".to_string()),
        (SystemId::InstrumentId(213), "HBAN".to_string()),
        (SystemId::InstrumentId(214), "HCA".to_string()),
        (SystemId::InstrumentId(215), "HD".to_string()),
        (SystemId::InstrumentId(216), "HES".to_string()),
        (SystemId::InstrumentId(217), "HIG".to_string()),
        (SystemId::InstrumentId(218), "HII".to_string()),
        (SystemId::InstrumentId(219), "HLT".to_string()),
        (SystemId::InstrumentId(220), "HOLX".to_string()),
        (SystemId::InstrumentId(221), "HON".to_string()),
        (SystemId::InstrumentId(222), "HPE".to_string()),
        (SystemId::InstrumentId(223), "HPQ".to_string()),
        (SystemId::InstrumentId(224), "HRL".to_string()),
        (SystemId::InstrumentId(225), "HSIC".to_string()),
        (SystemId::InstrumentId(226), "HST".to_string()),
        (SystemId::InstrumentId(227), "HSY".to_string()),
        (SystemId::InstrumentId(228), "HUM".to_string()),
        (SystemId::InstrumentId(229), "HWM".to_string()),
        (SystemId::InstrumentId(230), "IBM".to_string()),
        (SystemId::InstrumentId(231), "ICE".to_string()),
        (SystemId::InstrumentId(232), "IDXX".to_string()),
        (SystemId::InstrumentId(233), "IEX".to_string()),
        (SystemId::InstrumentId(234), "IFF".to_string()),
        (SystemId::InstrumentId(235), "ILMN".to_string()),
        (SystemId::InstrumentId(236), "INCY".to_string()),
        (SystemId::InstrumentId(237), "INTC".to_string()),
        (SystemId::InstrumentId(238), "INTU".to_string()),
        (SystemId::InstrumentId(239), "INVH".to_string()),
        (SystemId::InstrumentId(240), "IP".to_string()),
        (SystemId::InstrumentId(241), "IPG".to_string()),
        (SystemId::InstrumentId(242), "IQV".to_string()),
        (SystemId::InstrumentId(243), "IR".to_string()),
        (SystemId::InstrumentId(244), "IRM".to_string()),
        (SystemId::InstrumentId(245), "ISRG".to_string()),
        (SystemId::InstrumentId(246), "IT".to_string()),
        (SystemId::InstrumentId(247), "ITW".to_string()),
        (SystemId::InstrumentId(248), "IVZ".to_string()),
        (SystemId::InstrumentId(249), "J".to_string()),
        (SystemId::InstrumentId(250), "JBHT".to_string()),
        (SystemId::InstrumentId(251), "JCI".to_string()),
        (SystemId::InstrumentId(252), "JKHY".to_string()),
        (SystemId::InstrumentId(253), "JNJ".to_string()),
        (SystemId::InstrumentId(254), "JNPR".to_string()),
        (SystemId::InstrumentId(255), "JPM".to_string()),
        (SystemId::InstrumentId(256), "K".to_string()),
        (SystemId::InstrumentId(257), "KDP".to_string()),
        (SystemId::InstrumentId(258), "KEY".to_string()),
        (SystemId::InstrumentId(259), "KEYS".to_string()),
        (SystemId::InstrumentId(260), "KHC".to_string()),
        (SystemId::InstrumentId(261), "KIM".to_string()),
        (SystemId::InstrumentId(262), "KLAC".to_string()),
        (SystemId::InstrumentId(263), "KMB".to_string()),
        (SystemId::InstrumentId(264), "KMI".to_string()),
        (SystemId::InstrumentId(265), "KMX".to_string()),
        (SystemId::InstrumentId(266), "KO".to_string()),
        (SystemId::InstrumentId(267), "KR".to_string()),
        (SystemId::InstrumentId(268), "L".to_string()),
        (SystemId::InstrumentId(269), "LDOS".to_string()),
        (SystemId::InstrumentId(270), "LEN".to_string()),
        (SystemId::InstrumentId(271), "LH".to_string()),
        (SystemId::InstrumentId(272), "LHX".to_string()),
        (SystemId::InstrumentId(273), "LIN".to_string()),
        (SystemId::InstrumentId(274), "LKQ".to_string()),
        (SystemId::InstrumentId(275), "LLY".to_string()),
        (SystemId::InstrumentId(276), "LMT".to_string()),
        (SystemId::InstrumentId(277), "LNC".to_string()),
        (SystemId::InstrumentId(278), "LNT".to_string()),
        (SystemId::InstrumentId(279), "LOW".to_string()),
        (SystemId::InstrumentId(280), "LRCX".to_string()),
        (SystemId::InstrumentId(281), "LUMN".to_string()),
        (SystemId::InstrumentId(282), "LUV".to_string()),
        (SystemId::InstrumentId(283), "LVS".to_string()),
        (SystemId::InstrumentId(284), "LW".to_string()),
        (SystemId::InstrumentId(285), "LYB".to_string()),
        (SystemId::InstrumentId(286), "LYV".to_string()),
        (SystemId::InstrumentId(287), "MA".to_string()),
        (SystemId::InstrumentId(288), "MAA".to_string()),
        (SystemId::InstrumentId(289), "MAR".to_string()),
        (SystemId::InstrumentId(290), "MAS".to_string()),
        (SystemId::InstrumentId(291), "MCD".to_string()),
        (SystemId::InstrumentId(292), "MCHP".to_string()),
        (SystemId::InstrumentId(293), "MCK".to_string()),
        (SystemId::InstrumentId(294), "MCO".to_string()),
        (SystemId::InstrumentId(295), "MDLZ".to_string()),
        (SystemId::InstrumentId(296), "MDT".to_string()),
        (SystemId::InstrumentId(297), "MET".to_string()),
        (SystemId::InstrumentId(298), "META".to_string()),
        (SystemId::InstrumentId(299), "MGM".to_string()),
        (SystemId::InstrumentId(300), "MHK".to_string()),
        (SystemId::InstrumentId(301), "MKC".to_string()),
        (SystemId::InstrumentId(302), "MKTX".to_string()),
        (SystemId::InstrumentId(303), "MLM".to_string()),
        (SystemId::InstrumentId(304), "MMC".to_string()),
        (SystemId::InstrumentId(305), "MMM".to_string()),
        (SystemId::InstrumentId(306), "MNST".to_string()),
        (SystemId::InstrumentId(307), "MO".to_string()),
        (SystemId::InstrumentId(308), "MOH".to_string()),
        (SystemId::InstrumentId(309), "MOS".to_string()),
        (SystemId::InstrumentId(310), "MPC".to_string()),
        (SystemId::InstrumentId(311), "MPWR".to_string()),
        (SystemId::InstrumentId(312), "MRK".to_string()),
        (SystemId::InstrumentId(313), "MRNA".to_string()),
        (SystemId::InstrumentId(314), "MRO".to_string()),
        (SystemId::InstrumentId(315), "MS".to_string()),
        (SystemId::InstrumentId(316), "MSCI".to_string()),
        (SystemId::InstrumentId(317), "MSFT".to_string()),
        (SystemId::InstrumentId(318), "MSI".to_string()),
        (SystemId::InstrumentId(319), "MTB".to_string()),
        (SystemId::InstrumentId(320), "MTCH".to_string()),
        (SystemId::InstrumentId(321), "MTD".to_string()),
        (SystemId::InstrumentId(322), "MU".to_string()),
        (SystemId::InstrumentId(323), "NCLH".to_string()),
        (SystemId::InstrumentId(324), "NDAQ".to_string()),
        (SystemId::InstrumentId(325), "NDSN".to_string()),
        (SystemId::InstrumentId(326), "NEE".to_string()),
        (SystemId::InstrumentId(327), "NEM".to_string()),
        (SystemId::InstrumentId(328), "NFLX".to_string()),
        (SystemId::InstrumentId(329), "NI".to_string()),
        (SystemId::InstrumentId(330), "NKE".to_string()),
        (SystemId::InstrumentId(331), "NLOK".to_string()),
        (SystemId::InstrumentId(332), "NOC".to_string()),
        (SystemId::InstrumentId(333), "NOW".to_string()),
        (SystemId::InstrumentId(334), "NRG".to_string()),
        (SystemId::InstrumentId(335), "NSC".to_string()),
        (SystemId::InstrumentId(336), "NTAP".to_string()),
        (SystemId::InstrumentId(337), "NTRS".to_string()),
        (SystemId::InstrumentId(338), "NUE".to_string()),
        (SystemId::InstrumentId(339), "NVDA".to_string()),
        (SystemId::InstrumentId(340), "NVR".to_string()),
        (SystemId::InstrumentId(341), "NWL".to_string()),
        (SystemId::InstrumentId(342), "NWS".to_string()),
        (SystemId::InstrumentId(343), "NWSA".to_string()),
        (SystemId::InstrumentId(344), "NXPI".to_string()),
        (SystemId::InstrumentId(345), "O".to_string()),
        (SystemId::InstrumentId(346), "ODFL".to_string()),
        (SystemId::InstrumentId(347), "OGN".to_string()),
        (SystemId::InstrumentId(348), "OKE".to_string()),
        (SystemId::InstrumentId(349), "OMC".to_string()),
        (SystemId::InstrumentId(350), "ON".to_string()),
        (SystemId::InstrumentId(351), "ORCL".to_string()),
        (SystemId::InstrumentId(352), "ORLY".to_string()),
        (SystemId::InstrumentId(353), "OTIS".to_string()),
        (SystemId::InstrumentId(354), "OXY".to_string()),
        (SystemId::InstrumentId(355), "PARA".to_string()),
        (SystemId::InstrumentId(356), "PAYC".to_string()),
        (SystemId::InstrumentId(357), "PAYX".to_string()),
        (SystemId::InstrumentId(358), "PCAR".to_string()),
        (SystemId::InstrumentId(359), "PCG".to_string()),
        (SystemId::InstrumentId(360), "PEAK".to_string()),
        (SystemId::InstrumentId(361), "PEG".to_string()),
        (SystemId::InstrumentId(362), "PEP".to_string()),
        (SystemId::InstrumentId(363), "PFE".to_string()),
        (SystemId::InstrumentId(364), "PFG".to_string()),
        (SystemId::InstrumentId(365), "PG".to_string()),
        (SystemId::InstrumentId(366), "PGR".to_string()),
        (SystemId::InstrumentId(367), "PH".to_string()),
        (SystemId::InstrumentId(368), "PHM".to_string()),
        (SystemId::InstrumentId(369), "PKG".to_string()),
        (SystemId::InstrumentId(370), "PKI".to_string()),
        (SystemId::InstrumentId(371), "PLD".to_string()),
        (SystemId::InstrumentId(372), "PM".to_string()),
        (SystemId::InstrumentId(373), "PNC".to_string()),
        (SystemId::InstrumentId(374), "PNR".to_string()),
        (SystemId::InstrumentId(375), "PNW".to_string()),
        (SystemId::InstrumentId(376), "POOL".to_string()),
        (SystemId::InstrumentId(377), "PPG".to_string()),
        (SystemId::InstrumentId(378), "PPL".to_string()),
        (SystemId::InstrumentId(379), "PRU".to_string()),
        (SystemId::InstrumentId(380), "PSA".to_string()),
        (SystemId::InstrumentId(381), "PSX".to_string()),
        (SystemId::InstrumentId(382), "PTC".to_string()),
        (SystemId::InstrumentId(383), "PWR".to_string()),
        (SystemId::InstrumentId(384), "PXD".to_string()),
        (SystemId::InstrumentId(385), "PYPL".to_string()),
        (SystemId::InstrumentId(386), "QCOM".to_string()),
        (SystemId::InstrumentId(387), "QRVO".to_string()),
        (SystemId::InstrumentId(388), "RCL".to_string()),
        (SystemId::InstrumentId(389), "RE".to_string()),
        (SystemId::InstrumentId(390), "REG".to_string()),
        (SystemId::InstrumentId(391), "REGN".to_string()),
        (SystemId::InstrumentId(392), "RF".to_string()),
        (SystemId::InstrumentId(393), "RHI".to_string()),
        (SystemId::InstrumentId(394), "RJF".to_string()),
        (SystemId::InstrumentId(395), "RL".to_string()),
        (SystemId::InstrumentId(396), "RMD".to_string()),
        (SystemId::InstrumentId(397), "ROK".to_string()),
        (SystemId::InstrumentId(398), "ROL".to_string()),
        (SystemId::InstrumentId(399), "ROP".to_string()),
        (SystemId::InstrumentId(400), "ROST".to_string()),
        (SystemId::InstrumentId(401), "RSG".to_string()),
        (SystemId::InstrumentId(402), "RTX".to_string()),
        (SystemId::InstrumentId(403), "SBAC".to_string()),
        (SystemId::InstrumentId(404), "SBNY".to_string()),
        (SystemId::InstrumentId(405), "SBUX".to_string()),
        (SystemId::InstrumentId(406), "SCHW".to_string()),
        (SystemId::InstrumentId(407), "SEDG".to_string()),
        (SystemId::InstrumentId(408), "SEE".to_string()),
        (SystemId::InstrumentId(409), "SHW".to_string()),
        (SystemId::InstrumentId(410), "SIVB".to_string()),
        (SystemId::InstrumentId(411), "SJM".to_string()),
        (SystemId::InstrumentId(412), "SLB".to_string()),
        (SystemId::InstrumentId(413), "SNA".to_string()),
        (SystemId::InstrumentId(414), "SNPS".to_string()),
        (SystemId::InstrumentId(415), "SO".to_string()),
        (SystemId::InstrumentId(416), "SPG".to_string()),
        (SystemId::InstrumentId(417), "SPGI".to_string()),
        (SystemId::InstrumentId(418), "SRE".to_string()),
        (SystemId::InstrumentId(419), "STE".to_string()),
        (SystemId::InstrumentId(420), "STT".to_string()),
        (SystemId::InstrumentId(421), "STX".to_string()),
        (SystemId::InstrumentId(422), "STZ".to_string()),
        (SystemId::InstrumentId(423), "SWK".to_string()),
        (SystemId::InstrumentId(424), "SWKS".to_string()),
        (SystemId::InstrumentId(425), "SYF".to_string()),
        (SystemId::InstrumentId(426), "SYK".to_string()),
        (SystemId::InstrumentId(427), "SYY".to_string()),
        (SystemId::InstrumentId(428), "T".to_string()),
        (SystemId::InstrumentId(429), "TAP".to_string()),
        (SystemId::InstrumentId(430), "TDG".to_string()),
        (SystemId::InstrumentId(431), "TDY".to_string()),
        (SystemId::InstrumentId(432), "TECH".to_string()),
        (SystemId::InstrumentId(433), "TEL".to_string()),
        (SystemId::InstrumentId(434), "TER".to_string()),
        (SystemId::InstrumentId(435), "TFC".to_string()),
        (SystemId::InstrumentId(436), "TFX".to_string()),
        (SystemId::InstrumentId(437), "TGT".to_string()),
        (SystemId::InstrumentId(438), "TJX".to_string()),
        (SystemId::InstrumentId(439), "TMO".to_string()),
        (SystemId::InstrumentId(440), "TMUS".to_string()),
        (SystemId::InstrumentId(441), "TPR".to_string()),
        (SystemId::InstrumentId(442), "TRGP".to_string()),
        (SystemId::InstrumentId(443), "TRMB".to_string()),
        (SystemId::InstrumentId(444), "TROW".to_string()),
        (SystemId::InstrumentId(445), "TRV".to_string()),
        (SystemId::InstrumentId(446), "TSCO".to_string()),
        (SystemId::InstrumentId(447), "TSLA".to_string()),
        (SystemId::InstrumentId(448), "TSN".to_string()),
        (SystemId::InstrumentId(449), "TT".to_string()),
        (SystemId::InstrumentId(450), "TTWO".to_string()),
        (SystemId::InstrumentId(451), "TWTR".to_string()),
        (SystemId::InstrumentId(452), "TXN".to_string()),
        (SystemId::InstrumentId(453), "TXT".to_string()),
        (SystemId::InstrumentId(454), "TYL".to_string()),
        (SystemId::InstrumentId(455), "UAL".to_string()),
        (SystemId::InstrumentId(456), "UDR".to_string()),
        (SystemId::InstrumentId(457), "UHS".to_string()),
        (SystemId::InstrumentId(458), "ULTA".to_string()),
        (SystemId::InstrumentId(459), "UNH".to_string()),
        (SystemId::InstrumentId(460), "UNP".to_string()),
        (SystemId::InstrumentId(461), "UPS".to_string()),
        (SystemId::InstrumentId(462), "URI".to_string()),
        (SystemId::InstrumentId(463), "USB".to_string()),
        (SystemId::InstrumentId(464), "V".to_string()),
        (SystemId::InstrumentId(465), "VFC".to_string()),
        (SystemId::InstrumentId(466), "VICI".to_string()),
        (SystemId::InstrumentId(467), "VLO".to_string()),
        (SystemId::InstrumentId(468), "VMC".to_string()),
        (SystemId::InstrumentId(469), "VNO".to_string()),
        (SystemId::InstrumentId(470), "VRSK".to_string()),
        (SystemId::InstrumentId(471), "VRSN".to_string()),
        (SystemId::InstrumentId(472), "VRTX".to_string()),
        (SystemId::InstrumentId(473), "VTR".to_string()),
        (SystemId::InstrumentId(474), "VTRS".to_string()),
        (SystemId::InstrumentId(475), "VZ".to_string()),
        (SystemId::InstrumentId(476), "WAB".to_string()),
        (SystemId::InstrumentId(477), "WAT".to_string()),
        (SystemId::InstrumentId(478), "WBA".to_string()),
        (SystemId::InstrumentId(479), "WBD".to_string()),
        (SystemId::InstrumentId(480), "WDC".to_string()),
        (SystemId::InstrumentId(481), "WEC".to_string()),
        (SystemId::InstrumentId(482), "WELL".to_string()),
        (SystemId::InstrumentId(483), "WFC".to_string()),
        (SystemId::InstrumentId(484), "WHR".to_string()),
        (SystemId::InstrumentId(485), "WM".to_string()),
        (SystemId::InstrumentId(486), "WMB".to_string()),
        (SystemId::InstrumentId(487), "WMT".to_string()),
        (SystemId::InstrumentId(488), "WRB".to_string()),
        (SystemId::InstrumentId(489), "WRK".to_string()),
        (SystemId::InstrumentId(490), "WST".to_string()),
        (SystemId::InstrumentId(491), "WTW".to_string()),
        (SystemId::InstrumentId(492), "WY".to_string()),
        (SystemId::InstrumentId(493), "WYNN".to_string()),
        (SystemId::InstrumentId(494), "XEL".to_string()),
        (SystemId::InstrumentId(495), "XOM".to_string()),
        (SystemId::InstrumentId(496), "XRAY".to_string()),
        (SystemId::InstrumentId(497), "XYL".to_string()),
        (SystemId::InstrumentId(498), "YUM".to_string()),
        (SystemId::InstrumentId(499), "ZBH".to_string()),
        (SystemId::InstrumentId(500), "ZBRA".to_string()),
        (SystemId::InstrumentId(501), "ZION".to_string()),
        (SystemId::InstrumentId(502), "ZTS".to_string()),
    ]),
});
