[workspace]
resolver = "1"
members = [
    "gui",
    "plus_modeled",
    "plus_utils"
]

[profile.release]
debug = true

# [[workspace.metadata.leptos]]
# name = "plus-leptos"
# lib-package = "plus_client"
